using TMPro;
using UnityEngine;

public class WelcomeScreen : MonoBehaviour
{
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    public GameObject forwardButton;
    public GameObject backButton;
    public GameObject confirmButton;

    public GameObject scrollPanel;

    public bool DISABLE_WELCOME_SCREEN = false;

    private string[] infoTexts = new string[] {
        "Sie befinden sich in der Steuerzentrale eines Kernreaktors. Ihre Aufgaben umfassen die √úberwachung der Systeme, die Steuerung der Energieproduktion und die Gew√§hrleistung der Sicherheit. Ihnen stehen folgende Elemente zur Verf√ºgung:",
        "üìü Hauptkonsole:\nZentrale Steuereinheit zur Regulierung des Reaktors und √úberwachung der Systemparameter.",
        "üí° Statuslampen:\nInformieren Sie √ºber den aktuellen Zustand der Reaktorkomponenten.",
        "üìã Clipboards:\nStandartverfahren verschiedener Szenarien. Starten Sie ein Szenario durch Bet√§tigen der () Taste",
        "üîç Gazeguiding Panel:\nEs stehen eine Reihe von unterst√ºzenden F√ºhrungselementen zur Verf√ºgung. Diese K√∂nnen nach belieben ausgew√§hlt werden",
        "üö™ T√ºr:\nVollst√§ndiges Zur√ºcksetzen der Simulation, um verschiedene Szenarien erneut zu durchlaufen oder Fehler zu korrigieren.",
        "Machen Sie sich bereit, die Kontrolle zu √ºbernehmen - die Sicherheit des Reaktors liegt in Ihren H√§nden! üî•‚ö°"
    };

    void Start()
    {
        if (DISABLE_WELCOME_SCREEN){
            this.gameObject.SetActive(false);
            return;          
        }
        backButton.SetActive(false);
        confirmButton.SetActive(true);
        scrollPanel.GetComponent<TextMeshProUGUI>().text = infoTexts[0];
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void Next()
    {
        int currentTextIndex = System.Array.IndexOf(infoTexts, scrollPanel.GetComponent<TextMeshProUGUI>().text);
        Debug.Log(currentTextIndex);
        if (currentTextIndex < infoTexts.Length - 1)
        {
            scrollPanel.GetComponent<TextMeshProUGUI>().text = infoTexts[currentTextIndex + 1];
        }
        if (currentTextIndex == infoTexts.Length - 2)
        {
            forwardButton.SetActive(false);
            //confirmButton.SetActive(true);
        }
        if (currentTextIndex >= 0)
        {
            backButton.SetActive(true);
        }
    }

    public void Previous()
    {
        int currentTextIndex = System.Array.IndexOf(infoTexts, scrollPanel.GetComponent<TextMeshProUGUI>().text);
        if (currentTextIndex > 0)
        {
            scrollPanel.GetComponent<TextMeshProUGUI>().text = infoTexts[currentTextIndex - 1];
        }
        if (currentTextIndex == 1)
        {
            backButton.SetActive(false);
        }
        if (currentTextIndex < infoTexts.Length - 1)
        {
            forwardButton.SetActive(true);
            //confirmButton.SetActive(false);
        }
    }

    public void Confirm()
    {
        this.gameObject.SetActive(false);
    }
}
